// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwVc_Hti7HXERYLJVLeiSR5xpiz3flEYI',
    appId: '1:582909327426:web:0b9308205abad3a29915db',
    messagingSenderId: '582909327426',
    projectId: 'flutter-application-1-ef6b4',
    authDomain: 'flutter-application-1-ef6b4.firebaseapp.com',
    storageBucket: 'flutter-application-1-ef6b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdmL0BnBEfcG0jw8MCAU0wvtRMeAMfzDs',
    appId: '1:582909327426:android:87aa28cfc6fd880c9915db',
    messagingSenderId: '582909327426',
    projectId: 'flutter-application-1-ef6b4',
    storageBucket: 'flutter-application-1-ef6b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFNTCne-hV6caV_KS1Psbs6_EaWShxBss',
    appId: '1:582909327426:ios:741684793bca5af79915db',
    messagingSenderId: '582909327426',
    projectId: 'flutter-application-1-ef6b4',
    storageBucket: 'flutter-application-1-ef6b4.appspot.com',
    iosBundleId: 'com.example.weChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFNTCne-hV6caV_KS1Psbs6_EaWShxBss',
    appId: '1:582909327426:ios:741684793bca5af79915db',
    messagingSenderId: '582909327426',
    projectId: 'flutter-application-1-ef6b4',
    storageBucket: 'flutter-application-1-ef6b4.appspot.com',
    iosBundleId: 'com.example.weChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwVc_Hti7HXERYLJVLeiSR5xpiz3flEYI',
    appId: '1:582909327426:web:0b9308205abad3a29915db',
    messagingSenderId: '582909327426',
    projectId: 'flutter-application-1-ef6b4',
    authDomain: 'flutter-application-1-ef6b4.firebaseapp.com',
    storageBucket: 'flutter-application-1-ef6b4.appspot.com',
  );
}
